---
# ansible/roles/crowdsec/handlers/main.yml

- name: reload crowdsec
  systemd:
    name: crowdsec
    state: reloaded

- name: reload crowdsec-firewall-bouncer
  systemd:
    name: crowdsec-firewall-bouncer
    state: restarted
